[workspace]
members = ["contracts/lending", "contracts/collateral_vault", "contracts/margin_positions"]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
