mod test_get_interest_rate;
mod test_get_supported_tokens;
mod test_get_tokens_interest_rate_model_params;
mod test_set_get_price;
mod test_get_liquidity_rate;
mod test_get_mm_token_price;
mod test_get_current_liquidity_index_ln;
mod test_get_deposit;
