mod test_fail_deposit_cw20_not_enough_balance;
mod test_fail_deposit_insufficient_balance_after_successful_deposit;
mod test_fail_deposit_insufficient_initial_balance;
mod test_success_deposit_cw20_by_parts;
mod test_success_deposits_of_diff_token;
mod test_success_deposits_of_one_token;
