mod test_fail_redeem_more_than_deposited;
mod test_success_redeem_diff_token;
mod test_success_redeem_one_token_by_parts;
mod test_success_redeem_one_token_whole_deposit;
mod test_success_cw20_redeem_by_parts;
mod test_success_cw20_redeem_whole_deposit;
mod test_fail_cw20_redeem_more_than_deposited;
